#! /bin/bash

# Install v4l2loopback module if not loaded.  Defaults to creating /dev/videoX
# and /dev/videoX+1 loopback devices, where X is the next available video
# number.  To specify different video numbers, set VID1 and VID2 environment
# variables before running the script. 

: ${progn:=${0##*/}}
type -p pd || pd () {
    ${DEBUG:-false} && echo -ne "[$progn-$BASH_LINENO] $*\n" >&2 ; true
}
type -p pi || pi () { echo -ne "[$progn] $*\n" >&2 ; true ; }

runfile=/tmp/v4l2loopback.run

# modCheck checks if the v4l2loopback module is loaded. Sets VID1, VID2, and modOptions.
modCheck () {
    if lsmod | grep -q v4l2loopback ; then
        pi "v4l2loopback module is already loaded." 
        pushd /sys/devices/virtual/video4linux/ &> /dev/null
        vids=( video* )
        export VID1=${vids[0]#video}
        export VID2=${vids[1]#video}
        export modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
        pi "Using existing loopback devices: /dev/video$VID1 and /dev/video$VID2" 
        echo -en "VID1=$VID1\nVID2=$VID2\n" > "$runfile"
        popd &> /dev/null

        return 0
    else
        pi "v4l2loopback module is not loaded." 
        ${DEBUG:-false} && modinfo -n v4l2loopback

        # Get the next available video number for loopback devices
        export VID1=${VID1:-$( vids=( /dev/video* ) ; echo $(( ${vids[-1]#/dev/video} +1 )) )}
        export VID2=${VID2:-$(( VID1 + 1 ))}
        export modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
        pd "Next available video numbers for loopback devices: $VID1 and $VID2"
        [ -f "$runfile" ] && rm -f "$runfile"

        return 1
    fi
}

# Load the v4l2loopback module.
modLoad () {
    modCheck && return 0
    pi "Attempting to load v4l2loopback module with sudo privileges..." 
    if sudo modprobe v4l2loopback "${modOptions[@]}" ; then
        pd "v4l2loopback module loaded successfully."
        modCheck
        return 0
    else
        pd "Failed to load v4l2loopback module."
        return 1
    fi
}

# Remove the v4l2loopback module.
modDelete () {
    pi "delete doing modCheck"
    if modCheck ; then
        pi "Attempting to remove v4l2loopback module with sudo privileges..." 
        if sudo modprobe -r v4l2loopback ; then
            pi "v4l2loopback module removed successfully." 
            modCheck
            return 0
        else
            pi "Failed to remove v4l2loopback module." 
            return 1
        fi
    else
        pd "v4l2loopback module is not loaded, nothing to remove."
        return 0
    fi
}

main () {

    usage () {
    cat <<_EOL_

Usage: $progn <remove>

Load the v4l2loopback module to create split video devices.
Run this script with the 'remove' argument to unload the
module.

This script set VID1 and VID2 to the next available video numbers for loopback
devices. If the module is already loaded, it will use the existing loopback
devices and set VID1 and VID2 accordingly.  State information is saved to $runfile.

_EOL_
        exit 1
    }

    
    case "$1" in
        -r|remove) modDelete ; exit $? ;;
        -h|--help) usage ;;
    esac

    modLoad || {
        pi "Error: Unable to load v4l2loopback module. Exiting." 
        exit 1
    }

    pd "To remove the v4l2loopback module, run this script with the 'remove' argument: $0 remove"

}

return &> /dev/null || main "$@"  # Run main() if called as a script

